### ISSUE TITLE
Sample site has  YSOD

### ISSUE THREAD

**Issue by brendan-rice** [pedropaf/saas-ecom#1]
Thanks for creating this project it looks really helpful, I'll be looking at it more over the next week.

I tried to register with the sample site (https://saas-ecom.azurewebsites.net/Account/Register) but got a YSOD, though to you might like to know.

**Comment by pedropaf** [comment]
Hi Brendan, glad you liked it. I'm aware of the error. I'm currently working on a few tweaks to release version 1, and working on a new sample and preparing a detail tutorial about it. In the next few weeks the new sample will replace the current site. Thanks!!

**Comment by brendan-rice** [comment]
Great pedro, has much changed as I am about to start a project that I was going to base off your example?

On 4 February 2015 at 01:31:56, Pedro Alonso (notifications@github.com) wrote:

Hi Brendan, glad you liked it. I'm aware of the error. I'm currently working on a few tweaks to release version 1, and working on a new sample and preparing a detail tutorial about it. In the next few weeks the new sample will replace the current site. Thanks!!

**Comment by pedropaf** [comment]
Not a lot has changed, but it is more stable and I've added some fixes and improvements based on a project that I'm about to launch. If you can wait about a week, the release 1.0 will be available on NuGet.

**Comment by pedropaf** [comment]
@brendan-rice I just published version 1.0 to NuGet if you want to give it a go.

**Comment by brendan-rice** [comment]
Good man, perfect timing, will give it a go next week

On 6 February 2015 at 14:09:21, Pedro Alonso (notifications@github.com) wrote:

@brendan-rice I just published version 1.0 to NuGet if you want to give it a go.

**Comment by pedropaf** [comment]
@brendan-rice did you have a chance to test SAAS Ecom? I should be publishing the new demo site pretty soon. The source code is in pedropaf/saas-ecom-my-notes-sample it's almost ready...

**Comment by brendan-rice** [comment]
Not yet, I'll be looking at this over the next few days though and will give you feedback.

I might have to integrate it into a CMS with a different membership system, are there any hooks for that?

It will be similar to the old asp.net membership system (not identity).

**Comment by pedropaf** [comment]
No, only Identity.

**Comment by pedropaf** [comment]
The new demo site is up and also available on GitHub. A long tutorial about it coming soon.
