### ISSUE TITLE
Both the latest NuGet and Demo site YSOD

### ISSUE THREAD

**Issue by MagnusJohansson** [pedropaf/saas-ecom#2]
Hi,

just installed the NuGet packages and when trying to add a credit card, I get:

Server Error in '/' Application.
You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Stripe.StripeException: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.

Source Error:
Line 205:      {
Line 206:        var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
Line 207:        await CardService.AddAsync(user, model.CreditCard);
Line 208:
Line 209:        // TempData.Add("flash", new FlashSuccessViewModel("Your credit card has been saved successfully."));

This happens on your live demo site as well (peeking at your Elmah log):
Host    Code    Type    Error   User    Date    Time
RD000D3A108AAF  0   Stripe  You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/. Details…

Any ideas how to fix this?

Thanks.

**Comment by pedropaf** [comment]
Hi @MagnusJohansson you have to add your Stripe API Keys to Web.config as explained here: http://www.pedroalonso.net/blog/2014/11/13/saas-ecom-available-in-nuget/

The demo site is failing for a different reason and I'm planning to fix it as soon as I have some time.

Thanks,
Pedro

**Comment by MagnusJohansson** [comment]
Hi, I have already added the API keys as described  in the blog post, so there must be something else.
I'm curious to know what the "different reason" is that causes the exact same error message that I'm seeing. 
Can you elaborate?

Thanks.

**Comment by pedropaf** [comment]
I haven't actually run this sample in a while, hopefully I'll have some time to have a look on the weekend and get back to you.

**Comment by hyrmedia** [comment]
Same happened to me with the Nuget package. I went back to including the source directly in my project for now. Still working on solving some other issues though so I can't tell you if the latest version is more functional.

**Comment by pedropaf** [comment]
@hyrmedia @MagnusJohansson I just tested the version in SaasDemo and it works for me. A few things to consider:
- Double check that you've created a subscription plan in Stripe.
- Create the subscription plan in the Plan table, with the same Id given to the plan in stripe (look at seed method).
- Checkout the full demo repository. Check which version of SaasEcom.Core and SaasEcomFrontEnd you are using. I'm trying to keep them compatible with the same version number.

I'm also preparing a new demo and long article explaining how I'm building it.

Let me know if this fixes your issues. Thanks

**Comment by pedropaf** [comment]
@hyrmedia @MagnusJohansson I have updated SaasDemo to SaasEcom 1.1.3 and it works fine.

The error that you mentioned, I've seen it too. It's confusing, but that's what Stripe is sending back. Double check that you're not sending a StripeCustomerId that is null, or a subscription plan that is null for some reason, that seemed to be the cause for the exception described earlier.

Thanks

**Comment by pedropaf** [comment]
The new demo site is up and also available on GitHub. A long tutorial about it coming soon.
