### ISSUE TITLE
Can't Build, 3 Errors

### ISSUE THREAD

**Issue by danrovito** [pedropaf/saas-ecom#4]
I followed the blog post here http://www.pedroalonso.net/blog/2014/11/13/saas-ecom-available-in-nuget/

I am getting these three errors

Error   1   'SaasEcom.Core.Infrastructure.Facades.SubscriptionsFacade' does not contain a constructor that takes 4 arguments    C:\Code\GitHub\aircss\aircss\Controllers\AccountController.cs   64  72  aircss

Error   2   'aircss.Models.ApplicationUser' does not contain a definition for 'CreatedAt'   C:\Code\GitHub\aircss\aircss\Controllers\AccountController.cs   173 95  aircss

Error   3   'SaasEcom.Core.Infrastructure.Facades.SubscriptionsFacade' does not contain a definition for 'SubscribeNewUserAsync' and no extension method 'SubscribeNewUserAsync' accepting a first argument of type 'SaasEcom.Core.Infrastructure.Facades.SubscriptionsFacade' could be found (are you missing a using directive or an assembly reference?) C:\Code\GitHub\aircss\aircss\Controllers\AccountController.cs   186 71  aircss

Any help is appreciated

**Comment by pedropaf** [comment]
It changed slighly after the last version I published. I'll try to update the post to work with the latest version tomorrow. Thanks

**Comment by pedropaf** [comment]
For the time being, the new signature is like this:

```
    private SubscriptionsFacade _subscriptionsFacade;
    private SubscriptionsFacade SubscriptionsFacade
    {
        get
        {
            return _subscriptionsFacade ?? (_subscriptionsFacade = new SubscriptionsFacade(
                new SubscriptionDataService<ApplicationDbContext, ApplicationUser>
                    (HttpContext.GetOwinContext().Get<ApplicationDbContext>()),
                new SubscriptionProvider(ConfigurationManager.AppSettings["StripeApiSecretKey"]),
                new CardProvider(ConfigurationManager.AppSettings["StripeApiSecretKey"],
                    new CardDataService<ApplicationDbContext, ApplicationUser>(Request.GetOwinContext().Get<ApplicationDbContext>())),
                new CardDataService<ApplicationDbContext, ApplicationUser>(Request.GetOwinContext().Get<ApplicationDbContext>()),
                new CustomerProvider(ConfigurationManager.AppSettings["StripeApiSecretKey"]),
                new SubscriptionPlanDataService<ApplicationDbContext, ApplicationUser>(Request.GetOwinContext().Get<ApplicationDbContext>()),
                new ChargeProvider(ConfigurationManager.AppSettings["StripeApiSecretKey"])));
        }
    }
```

**Comment by danrovito** [comment]
Any tips on why CreatedAt or SubscribeNewUserAsync won't work?

user = (ApplicationUser)await SubscriptionsFacade.SubscribeNewUserAsync(user, model.SubscriptionPlan.ToLower());

var user = new ApplicationUser { UserName = model.Email, Email = model.Email, CreatedAt = DateTime.UtcNow };

**Comment by danrovito** [comment]
reread your latest comment. I'll check back tomorrow

**Comment by danrovito** [comment]
Pedro, will this update take place as a nuget update?

**Comment by pedropaf** [comment]
Hi Dan,

The problem happens at the moment because I updated the nuget package. There's a small change that it isn't reflected in the blogpost. I'll check that the sample in GitHub works with the latest release from Nuget.

**Comment by danrovito** [comment]
Thank you. I used the nuget package to get started. The demo sln on
GitHub didn't
work either

**Comment by pedropaf** [comment]
I have just updated Saas-ecom-demo repository to work with SaasEcom 1.1.3. If you check out the repository you can check the differences with your code and fix it. It's still very similar to the instructions on the blog post that I wrote a few months ago.

**Comment by danrovito** [comment]
Thank you for this.  It's working great.  Is the admin portal not in 1.1.3?

**Comment by pedropaf** [comment]
The admin is gone, it hasn't been on any NuGet package. It was very basic and not adding anything that you can quickly do from Stripe admin portal. You can easily add Intercom observe and you have more valuable data than the stuff that you were getting from the admin.
