### ISSUE TITLE
Registration Fails

### ISSUE THREAD

**Issue by benfoster** [pedropaf/saas-ecom#6]
The `SaasEcomUser` class defines non-nullable `RegistrationDate` and `LastLoginDate` properties. Anyone installing saas-ecom into their project will need to update their Registration action to define the user as below:

```
var user = new ApplicationUser { UserName = model.Email, Email = model.Email, RegistrationDate = DateTime.UtcNow, LastLoginTime = DateTime.UtcNow  };
```

Worth mentioning this on the docs.

**Comment by pedropaf** [comment]
Done! Thanks @benfoster

**Comment by pedropaf** [comment]
@benfoster I just made a small release where those 2 fields are nullable.

Also, how's your RavenDB implementation going? Already done? I still want to do the abstraction of the data layer and EF Identity from the Core package so other persistence layers can be plugged in as you suggested, but very busy these days...

**Comment by benfoster** [comment]
My RavenDB implementation is working but needs some tidying up. My implementation differs slightly in that we didn't want to push the trials through Stripe but there are many similarities to Saas-ecom. I'll drop you an email as I want to know if we can combine our efforts on another project I'm working on.
