### ISSUE TITLE
GetCountryFromIP fails when running locally

### ISSUE THREAD

**Issue by benfoster** [pedropaf/saas-ecom#7]
If you're running locally and using IPv6 then the call to `GeoLocation.GetCountryFromIP` will fail since the IP will be an empty string.

I changed this to: 

```
IPAddressCountry = string.IsNullOrEmpty(userIP) ? null : GeoLocationHelper.GetCountryFromIP(userIP),
```

To get everything running locally.

Note that this was for the MyNotes example.

**Comment by pedropaf** [comment]
Thanks @benfoster I have checked this in too.
